[package]
name = "smolid"
version = "0.1.0"
edition = "2021"
license = "MIT"
documentation = "https://github.com/dotvezz/smolid-rs"
description = "A Rust implementation of smolid"

[dependencies]
base32 = "0.5.1"
rand = "0.9.2"
